os:
- linux
language: elixir
elixir:
- 1.3.4
otp_release:
- 19.1
notifications:
  email: false
before_script:
- 'apt-get -y install nodejs'
- 'npm install -g npm bower brunch'
- gem install sass
script:
- echo "building clients"
- make rebuild
- echo "getting cibash scripts"
- wget https://github.com/timCF/cibash/archive/0.0.7.tar.gz
- tar xvzf ./0.0.7.tar.gz
- echo "START elixir build script"
- "./cibash-0.0.7/elixir_yandex.sh studio studio rel"
- echo "END elixir build script"
